### ISSUE TITLE
No support for released 2.2 branches

### ISSUE THREAD

**Issue by ElderFain** [cloudfoundry-community/swift-buildpack#11]
Hello,

It appears the manifest doesn't support the released & dev branches of 2.2

https://swift.org/builds/swift-2.2-release/ubuntu1404/swift-2.2-RELEASE/swift-2.2-RELEASE-ubuntu14.04.tar.gz

and 

https://swift.org/builds/swift-2.2-branch/ubuntu1404/swift-2.2.1-SNAPSHOT-2016-03-28-a/swift-2.2.1-SNAPSHOT-2016-03-28-a-ubuntu14.04.tar.gz

I believe translated_uri doesn't handle the directory layout for these resources to simply "plug" them into the manifest. 

It appears that the build pack supports either old "SNAPSHOT" but not the "RELEASE" itself.

**Comment by ElderFain** [comment]
Ah, I figured it out after stepping through the code a bit.
- name: swift
- version: 2.2-RELEASE
- uri: https://swift.org/builds/swift-2.2-release/ubuntu1404/swift-2.2-RELEASE/swift-2.2-RELEASE-ubuntu14.04.tar.gz
- md5: 8b641b49c8a3f61353cfd7218b02dc2e
- cf_stacks:
  - cflinuxfs2
- name: swift
- version: 2.2.1-SNAPSHOT-2016-03-28-a
- uri: https://swift.org/builds/swift-2.2-branch/ubuntu1404/swift-2.2.1-SNAPSHOT-2016-03-28-a/swift-2.2.1-SNAPSHOT-2016-03-28-a-ubuntu14.04.tar.gz
- md5: fc7df260606ae9d385afa55bd7a5a742
- cf_stacks:
  - cflinuxfs2

**Comment by briancroom** [comment]
@ElderFain The issue here is that this buildpack relies on the Swift Package Manager to perform the build, however that tool is not included on the Swift 2.2 release branch.
