### ISSUE TITLE
Unable to push the swift app.

### ISSUE THREAD

**Issue by krrrahul** [cloudfoundry-community/swift-buildpack#18]
I am trying to push the swift helloworld app in Cloudfoundary .But its throwing error .
 Attaching the screen shot for error.
Can you please look into the error.
![screen shot 02-13-17 at 04 25 pm](https://cloud.githubusercontent.com/assets/16372337/22881599/4e37fe66-f20d-11e6-8c37-2024caa56691.PNG)
 
Thanks in advance

**Comment by drnic** [comment]
@rahul221192 did you ever resolve this?
