### ISSUE TITLE
Need formal release of the buildpack with latest code

### ISSUE THREAD

**Issue by rolivieri** [cloudfoundry-community/swift-buildpack#7]
Hello, @drnic - Could you guys do a new release of the Swift buildpack with the latest buildpack code? Our team is currently attempting to use the latest release build (https://github.com/cloudfoundry-community/swift-buildpack/releases/tag/v1.0.2) but that version is somewhat outdated (Dec 10, 2015). For instance, using that old version, we cannot specify the latest version of Swift (DEVELOPMENT-SNAPSHOT-2016-02-03-a) in the .swift-version file. Any possibility of making a new release available early this week? Thanks.

**Comment by rolivieri** [comment]
@drnic, @briancroom - Hello guys, just following up on this issue. Would it be possible to do a formal release this week of this build pack with the latest code?

**Comment by briancroom** [comment]
I've just pushed a tag pointing the latest master for you, though in general I don't think it makes sense to do so very frequently, as we are still tracking unstable development snapshots. If you need a tagged releases for whatever reason, it seems like you ought to be able to simply fork and add push tags there?

**Comment by drnic** [comment]
I'm creating new zip files now. Instructions are at the bottom of the readme https://github.com/cloudfoundry-community/swift-buildpack#packaging

**Comment by drnic** [comment]
@briancroom if I built a CI pipeline that detected new swift snapshots, added them to manifest.yml, and cut new zip releases would that be handy?

**Comment by drnic** [comment]
Ok, hotel wifi is too slow for the downloads & and eventual upload of a cached zip; so I've added v1.0.3 uncached .zip to new release

https://github.com/cloudfoundry-community/swift-buildpack/releases/tag/v1.0.3

**Comment by drnic** [comment]
For the cached release zip file do we want ALL snapshots in it?

**Comment by drnic** [comment]
I've started a pipeline https://ci.starkandwayne.com/pipelines/swift-buildpack?groups=pipeline

**Comment by rolivieri** [comment]
@drnic Thanks for your help on this! I am thinking for the cached version, only the latest snapshot of the Swift binaries should suffice.

**Comment by drnic** [comment]
@rolivieri ok

@briancroom thoughts on what would go in the auto-built cached zip?

**Comment by drnic** [comment]
@jtarchie is there a way to have one manifest.yml for cached & another manifest.yml for uncached? Technically for uncached you're much happier to have a longer list of dependencies.

**Comment by drnic** [comment]
Found the `--use-custom-manifest` flag https://github.com/cloudfoundry/buildpack-packager#--use-custom-manifest

**Comment by drnic** [comment]
Ok, CI now has a `shipit` task that will cut a new release, and upload new zip files.

https://github.com/cloudfoundry-community/swift-buildpack/releases/tag/v1.0.3
https://ci.starkandwayne.com/pipelines/swift-buildpack/jobs/shipit/builds/16

**Comment by briancroom** [comment]
@drnic Wow! That's really neat. Thanks for setting that up.

I agree that only including a single version in the cached packages is sufficient. I'm actually a bit curious why people would use the cached version at all right now, since the whole toolchain is so far from production-readiness. I regard this buildpack effectively as a tech demo for developers to experiment with while things mature.
